# Generated by Django 5.1.7 on 2025-03-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_contestant',
            field=models.BooleanField(default=False),
        ),
    ]
