# Generated by Django 5.1.7 on 2025-04-02 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_is_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='custom_icon',
            field=models.FileField(blank=True, null=True, upload_to='custom_markers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
    ]
